dist: bionic

language: php

php: 7.4

install: composer require typo3/cms-core:"$TYPO3"
script: Build/Scripts/runTests.sh -s $TESTSUITE -p $PHP

jobs:
  include:
    - stage: "Early"
      name: "PHP CS Fixer"
      script: Build/Scripts/runTests.sh -s cglGit -n -p $PHP
      env:
        - TYPO3=^10.4
        - PHP=7.4

    - stage: "Unit Tests"
      name: "PHP 7.2 Unit"
      env:
        - TYPO3=^10.4
        - PHP=7.2
        - TESTSUITE=unit

    - name: "PHP 7.3 Unit"
      env:
        - TYPO3=^10.4
        - PHP=7.3
        - TESTSUITE=unit

    - name: "PHP 7.4 Unit"
      env:
        - TYPO3=^10.4
        - PHP=7.4
        - TESTSUITE=unit

    - name: "PHP 7.4 Unit"
      env:
        - TYPO3=~11.3.0
        - PHP=7.4
        - TESTSUITE=unit

    - name: "PHP 8.0 Unit"
      env:
        - TYPO3=~11.3.0
        - PHP=8.0
        - TESTSUITE=unit

    - name: "PHP 7.2 Unit Deprecated"
      env:
        - TYPO3=^10.4
        - PHP=7.2
        - TESTSUITE=unitDeprecated

    - name: "PHP 7.3 Unit Deprecated"
      env:
        - TYPO3=^10.4
        - PHP=7.3
        - TESTSUITE=unitDeprecated

    - name: "PHP 7.4 Unit Deprecated"
      env:
        - TYPO3=^10.4
        - PHP=7.4
        - TESTSUITE=unitDeprecated

    - name: "PHP 7.4 Unit Deprecated"
      env:
        - TYPO3=~11.3.0
        - PHP=7.4
        - TESTSUITE=unitDeprecated

    - name: "PHP 8.0 Unit Deprecated"
      env:
        - TYPO3=~11.3.0
        - PHP=8.0
        - TESTSUITE=unitDeprecated
