dist: bionic

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - TYPO3=^10.4
  - TYPO3=~11.4.0

jobs:
  exclude:
    - php: 8.0
      env: TYPO3=^10.4
    - php: 7.2
      env: TYPO3=~11.4.0
    - php: 7.3
      env: TYPO3=~11.4.0

install: composer require typo3/cms-core:"$TYPO3"
script:
  - .Build/vendor/phpunit/phpunit/phpunit -c Build/phpunit/UnitTests.xml
  - XDEBUG_MODE=off .Build/vendor/phpunit/phpunit/phpunit -c Build/phpunit/UnitTestsDeprecated.xml
