dist: bionic

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - TYPO3=^10.4
  - TYPO3=~11.2.0

jobs:
  exclude:
    - php: 7.2
      env: TYPO3=~11.2.0
    - php: 7.3
      env: TYPO3=~11.2.0

install: composer require typo3/cms-core:"$TYPO3"
script: .Build/vendor/phpunit/phpunit/phpunit -c .Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml .Build/Web/typo3conf/ext/mask/Tests/Unit
