services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $maskExtensionConfiguration: '@extensionconfiguration.mask'

  MASK\Mask\:
    resource: '../Classes/*'

  mask.loader:
    class: MASK\Mask\Loader\JsonLoader

  MASK\Mask\Loader\LoaderInterface: '@mask.loader'

  MASK\Mask\Definition\TableDefinitionCollection:
    factory:
      - '@mask.loader'
      - 'load'

  extensionconfiguration.mask:
    class: 'array'
    factory:
      - '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      - 'get'
    arguments:
      - 'mask'

  MASK\Mask\Controller\MaskController:
    tags: [ 'backend.controller' ]

  MASK\Mask\Controller\AjaxController:
    tags: [ 'backend.controller' ]

  MASK\Mask\Controller\FieldsController:
    tags: [ 'backend.controller' ]

  MASK\Mask\CodeGenerator\TyposcriptCodeGenerator:
    public: true

  MASK\Mask\CodeGenerator\TcaCodeGenerator:
    public: true

  MASK\Mask\Helper\InlineHelper:
    public: true

  MASK\Mask\Imaging\IconProvider\ContentElementIconProvider:
    public: true

  MASK\Mask\Hooks\PageLayoutViewDrawItem:
    public: true

  MASK\Mask\Form\FormDataProvider\TcaTypesShowitemMaskBeLayoutFields:
    public: true

  MASK\Mask\ItemsProcFuncs\CTypeList:
    public: true

  MASK\Mask\DataProcessing\MaskProcessor:
    public: true

  MASK\Mask\CodeGenerator\SqlCodeGenerator:
    tags:
      - name: event.listener
        identifier: 'sql-code-generator'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
        method: addDatabaseTablesDefinition
